# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yml file
# ===================================================================

spring:
  application:
    name: portfolio-server
  profiles:
    active: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: portfolioDB
      username:
      password:

# logging:
#   file: /Users/dupeyrat/Documents/Projects/logs/portfolio/java_app_log_file.log

server:
  port: 8443
  tomcat:
    accesslog:
      enabled: true
      directory: /Users/dupeyrat/Documents/Projects/logs/portfolio/accessLog
      prefix: access_log
  ssl:
    enable: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore-local.p12
    key-store-password: secret
    key-alias: tomcat
  servlet:
    context-path: /api/v1/

app:
  mail:
    login: test.porfolio.dupeyrat@gmail.com
    password: Test.1234
    smtp: smtp.gmail.com
    port: 587

