# ===================================================================
# Spring Boot configuration for the "PROD" profile.
#
# This configuration overrides the application.yml file
# ===================================================================

spring:
  application:
    name: portfolio-server
  data:
    mongodb:
      mongodb:
        host: ${MONGO_HOST}
        port: ${MONGO_PORT}
        database: portfolioDB
        username: ${MONGO_USERNAME}
        password: ${MONGO_PASSWORD}

# logging:
#  file: ${LOG_PATH}/java_app_log_file.log

server:
  port: 8443
  tomcat:
    accesslog:
      enabled: true
      directory: ${ACCESS_LOG_DIRECTORY}
      prefix: access_log
  ssl:
    enable: true
    key-store-type: PKCS12
    key-store: classpath:keystore/baeldung-prod.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_STORE_ALIAS}
  servlet:
    context-path: /api/v1/

app:
  mail:
    login: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}
    smtp: smtp.gmail.com
    port: 587