# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yml file
# ===================================================================

spring:
  application:
    name: portfolio-server
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost/portfolioDB

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /Users/dupeyrat/Documents/Projects/Logs/Portfolio
      prefix: access_log