name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish package
        run: mvn -B install --file portfolio-server/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t docker.pkg.github.com/portfolio-SERVER/porfolio-server:0.1-snapshot ./portfolio-server/
      - name: Push Image in Repo GITHUB
        run: docker push docker.pkg.github.com/portfolio-SERVER/porfolio-server:0.1-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
